[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sha3mac"
version = "0.1.0"
description = "CLI for HMAC-SHA-3 coursework"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]
